# Generated by Django 5.2.6 on 2025-09-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do produto', max_length=100)),
                ('vendedor', models.CharField(help_text='Nome do vendedor', max_length=100)),
                ('categoria', models.CharField(help_text='Categoria do produto', max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do produto', max_digits=8)),
                ('foto', models.ImageField(blank=True, help_text='Foto do produto', null=True, upload_to='fotos_produtos/')),
                ('descricao', models.TextField(help_text='Descrição do produto')),
            ],
        ),
    ]
