# Generated by Django 5.2.6 on 2025-09-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('ELE', 'Eletrônicos'), ('ROU', 'Roupas'), ('LIV', 'Livros'), ('MOV', 'Móveis'), ('OUT', 'Outros')], help_text='Categoria do produto', max_length=100),
        ),
    ]
