# Generated by Django 5.2.6 on 2025-09-24 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_produto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('ELE', 'Eletrônicos'), ('ROU', 'Roupas'), ('LIV', 'Livros'), ('MOV', 'Móveis'), ('OUT', 'Outros')], default='OUT', help_text='Categoria do produto', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='vendedor',
            field=models.ForeignKey(help_text='Vendedor do produto', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
