# Generated by Django 5.2.6 on 2025-10-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text='Preço do produto', max_digits=16),
        ),
    ]
