# Generated by Django 5.2.6 on 2025-10-03 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0002_alter_produto_preco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopraProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('id_comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprador', to=settings.AUTH_USER_MODEL)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('id_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
